openapi: 3.0.1
info:
  title: Stock Position and Market Value
  contact:
    email: dfrances@afdtech.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
paths:
  /auto-stock-position-market-value/{symbol}:
    get:
      summary: Find stock position and market value by symbol
      description: Returns a GetStockPositionAndMarketValueApiResponseDTO
      parameters:
      - name: symbol
        in: path
        description: name of the symbol
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStockPositionAndMarketValueApiResponseDTOAuto'
  /auto-stock-position-market-value/add:
    post:
      summary: Add a new Symbol
      description: Returns PostStockPositionAndMarketValueApiResponseDTO
      consumes :
        - application/json
      parameters :
        -in: body
        name : symbol
        description : The symbol to add
        schema :
          type: object
          properties:
            symbol:
              type: string
            quantity:
              type: number
              format: double
              currencyCode:
                type: string
              cost:
                type: number
                format: double
              marketValue:
                type: number
                format: double
      responses:
        201:
          description: Symbol created
        401:
          description: Symbol format not accepted

    
  
components:
  schemas:
    PostStockPositionAndMarketValueApiResponseDTOAuto:
      type: object
      properties:
        symbol:
          type: string
        quantity:
          type: number
          format: double
          currencyCode:
            type: string
          cost:
            type: number
            format: double
          marketValue:
            type: number
            format: double


    GetStockPositionAndMarketValueApiResponseDTOAuto:
      type: object
      properties:
        symbol:
          type: string
        quantity:
          type: number
          format: double
        currencyCode:
          type: string
        cost:
          type: number
          format: double
        marketValue:
          type: number
          format: double
